runtime: nodejs20
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /(.*\.(css|js|map|json|ico|png|jpg|svg|webp|woff|woff2|ttf|eot|gif|txt|html))$
  static_files: build/\1
  upload: build/.*\.(css|js|map|json|ico|png|jpg|svg|webp|woff|woff2|ttf|eot|gif|txt|html)$

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
